name: Build and Deploy Bot
on: 
  push:
    branches:
      - main
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      uses: actions/checkout@v3

      - name: Setup Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: 22

      - name: Install dependencies
      run: npm ci

      - name: Build Project
      run: npm run build

      - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bot-dist
        path: build/