name: Build and Deploy Bot

on:
  push:
    branches:
      - main  # change if your main branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # match your runtime

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: SFTP Upload
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.CYBRANCEE_HOST }}
          username: ${{ secrets.CYBRANCEE_USERNAME }}
          password: ${{ secrets.CYBRANCEE_PASSWORD }}
          port: ${{ vars.CYBRANCEE_PORT }}
          uploads: |
            ./build => ./home/container/build
            ./node_modules/ => ./home/container/node_modules
